sudo: false
language: python
python:
  - "3.4"
before_install:
  - export DISPLAY=:10
  - "sh -e /etc/init.d/xvfb start"
install:
  - "git fetch --unshallow"
  - "python bootstrap.py --setuptools-version=12.0.4"
  - "PATH=${TRAVIS_BUILD_DIR}/bin:${PATH} ./bin/buildout -c buildout-${BUILDOUT_TARGET}.cfg 2>/dev/null"
script:
  - "./bin/py.test_run_unittests_with_coverage"
  - "./bin/py.test_run_all"
  - "PATH=${TRAVIS_BUILD_DIR}/bin:${PATH} ./bin/protractor etc/protractorConfTravis.js"
notifications:
  email: false
after_success:
  - "./bin/coveralls"
cache:
  directories:
    - eggs
    - node_modules
env:
  matrix:
    - BUILDOUT_TARGET=meinberlin
    - BUILDOUT_TARGET=mercator
addons:
  firefox: "34.0"
